### ISSUE TITLE
feature request: support for Chinese characters

### ISSUE THREAD

**Issue by CyrusYip** [ridarf/ray-this#1]
raythis does not recognize Chinese characters.

```
print("你好")
```

<img width="520" alt="Uploaded using RayThis Extension" src="https://user-images.githubusercontent.com/60951091/109152903-14f86900-77a7-11eb-91c8-753bbafca895.png">

**Comment by ridafkih** [comment]
@CyrusYip Thanks for bringing this to my attention! This isn't a limitation with RayThis specifically, but it is an issue I will try to see resolved.

Ray.so uses the `atob` function to handle base64 decoding, which doesn't support Unicode. Specifically it doesn't support the encoding/decoding of "characters outside o the Latin1 range."

A better implementation for them would be to implement their own Unicode supporting base64 decoding on their website. I will bring this to their attention! 

```js
function b64DecodeUnicode(str) {
    // Going backwards: from bytestream, to percent-encoding, to original string.
    return decodeURIComponent(atob(str).split('').map(function(c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
    }).join(''));
}
```

This function by the user [brandonscript on StackOverflow](https://stackoverflow.com/a/30106551) supports non-Latin character decoding.

**Comment by ridafkih** [comment]
@PitNikola Would you be able to implement a better base64 decoding function on Ray.so?

**Comment by PitNikola** [comment]
Hey @ridarf, thanks for bringing it to our attention, I'll forward it to an engineer working on ray.so

**Comment by RSO** [comment]
Thanks for bringing this to our attention @CyrusYip and thanks for coming up with a fix @ridarf ! I've just pushed the fix, can you confirm that this now works?

**Comment by ridafkih** [comment]
@RSO Awesome, checked it out and it now works with non-Latin characters!
Thanks for the fix, issue closed.
