### ISSUE TITLE
Ray.so update

### ISSUE THREAD

**Issue by FSipiano** [ridarf/ray-this#2]
Hey! Just thought you would want to know that we added the ability to configure the language in [ray.so](http://ray.so) via the URL query parameters. This means that you are able to parse a particular language into the URL and the site will render accordingly. 

You can already do this with other query parameters such as the colors and padding as well as the background and dark mode toggles, and we are excited to see what you will create with this new configurable parameter.

[Set-language-from-url.mp4.zip](https://github.com/ridarf/raythis/files/6235921/Set-language-from-url.mp4.zip)

All parameters can be found in [this script command](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/create-image-from-code.sh) 

Please reach out to me if you have any questions!

Faye

**Comment by ridafkih** [comment]
I went ahead and added local automatic language detection by using the open file as the filetype reference in version 1.1.0! 
Thanks for the update, but just so you know it doesn't seem like "auto" has been functional since that last update!
