### ISSUE TITLE
They changed to hash router

### ISSUE THREAD

**Issue by tzdesign** [ridarf/ray-this#4]
Hi there,

they changed to hash router and your cool extension is not working anymore.

https://github.com/ridafkih/raythis/blob/833c4a516ab3ad1b2fce9b4160d54d47c51dab34/extension.js#L62

Can you change it to

```javascript
return "https://ray.so/#" + parameters;
```

**Comment by ridafkih** [comment]
@tzdesign Can you make a PR for this issue?

**Comment by tzdesign** [comment]
Tried it before I passed you the issue, is it disabled?

**Comment by luke-court** [comment]
I've made the pull request myself, tested it and it worked for me so should be all good to go. See more here #5

**Comment by ridafkih** [comment]
@LJ-Court @tzdesign Changes should be in v1.1.1 which was just published. Anyone care to test it for me? Otherwise I'll be able to do it in a few hours. c:

**Comment by luke-court** [comment]
okay sure will do

**Comment by luke-court** [comment]
Can confirm it works perfectly thank you
